[package]
name = "one-liner"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Marco <https://github.com/mtolk>"]
license = "MIT"
description = "One-liner is a package containing a helper function to fit text to the available width by adjusting the text size based upon the context, so thext fits on 1 line. This is useful in templates where you don't know the length of text that is supposed to fit in specific locations in your template."
repository = "https://github.com/mtolk/one-liner"
keywords = ["fit-text","width","no-wrap"]
categories = ["layout","text","utility"]
compiler = "0.12.0"
exclude = ["example.typ","example.pdf","example1.png"]